In [473]:
import numpy as np

In [474]:
array_data = [1,2,3,4,5,6]
array_one = np.array(array_data)
print(array_one)

[1 2 3 4 5 6]


In [475]:
print(type(array_one))

<class 'numpy.ndarray'>


In [476]:
list_two = [
    [1,2,3],
    [4,5,6]
]
array_two = np.array(list_two , dtype='float32')
array_two
# print(type(array_two))

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [477]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [478]:
np.zeros((3,5) , dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [479]:
np.ones((3,5) , dtype='float32')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [480]:
np.full((3,5) , 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [481]:
np.full((3,5) , 4 , dtype='float64')

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [482]:
np.arange(0,20,2)
# 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [483]:
np.random.random((3,3))


array([[0.7682812 , 0.67199501, 0.82699225],
       [0.49306329, 0.26326075, 0.20345245],
       [0.05757952, 0.74697812, 0.34277576]])

In [484]:
np.random.normal(0,1,(3,3))

array([[-1.69731045,  0.01529148, -0.45957371],
       [ 0.07511416,  0.73949823,  1.25800834],
       [-0.88307821, -1.36251338, -1.33390269]])

In [485]:
np.random.normal(0,1,(3,3))
# Mean 0 and standard deviation in range of one

array([[ 1.38331008, -2.08711937,  0.4180547 ],
       [ 2.08875999,  0.24899768,  0.92809583],
       [-1.88549095, -0.28421954, -1.14970495]])

In [486]:
np.random.randint(1,10,(3,3))

array([[3, 1, 1],
       [7, 7, 9],
       [1, 9, 6]])

In [487]:
array_two.shape


(2, 3)

In [488]:
array_two.size

6

In [489]:
array_two.dtype

dtype('float32')

In [490]:
array_two.itemsize

4

In [491]:
array_two.ndim

2

In [492]:
sample_array = [[1,2,3,4],[5,6,7,8],[9,1,2,3]]
np_array = np.array(sample_array)

In [493]:
print(f"Dimension of the array is : {np_array.ndim}")
print(f"Size of the array is : {np_array.shape}")
print(f"RC of the array is : {np_array.size}")
print(f"Datatype of the array is : {np_array.dtype}")

Dimension of the array is : 2
Size of the array is : (3, 4)
RC of the array is : 12
Datatype of the array is : int64


In [494]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
array_3d
print(f"Dimension of the array is : {array_3d.ndim}")
print(f"Size of the array is : {array_3d.shape}")

Dimension of the array is : 3
Size of the array is : (2, 2, 3)


In [495]:
array_3d = np.array([[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]])
array_3d
print(array_3d.ndim)

4


In [496]:
# Creating Array
class Array:
    def __init__(self, data_type, initial_capacity=10):
        self.data_type = data_type
        self.capacity = initial_capacity
        self.size = 0
        self.elements = [None] * self.capacity

    def append(self, element):
        if not isinstance(element, self.data_type):
            raise TypeError(f"Invalid data type. Expected {self.data_type}, got {type(element)}")
        if self.size == self.capacity:
            self._resize()
        self.elements[self.size] = element
        self.size += 1

    def __getitem__(self, index):
        if index < 0 or index >= self.size:
            raise IndexError("Index out of range")
        return self.elements[index]

    def __len__(self):
        return self.size

    def _resize(self):
        self.capacity *= 2
        new_elements = [None] * self.capacity
        for i in range(self.size):
            new_elements[i] = self.elements[i]
        self.elements = new_elements


arr = Array(str)
# arr.append(1)
# arr.append(2)
# arr.append(3)


arr.append("four")
# arr
arr.__getitem__(0)
arr.__len__()
# arr.elements
# for data in arr:
#     print(data)

1

In [497]:
# Create a array of random values
np.empty((2,3))

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [498]:
# Create a range with given interval
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [499]:
arr_01 = np.array([1,2,3,4,5])
print(arr_01)
# arr_02 = np.array([1,2,3,'Sandip'] , dtype=int)
# arr_02
arr_03 = np.array([1,2,3,4,'Sandip'] ,dtype=object)
arr_03

[1 2 3 4 5]


array([1, 2, 3, 4, 'Sandip'], dtype=object)

In [500]:
# Array Indexing 
a = np.array([0,1,2,3,4])

print(f"First Index Element: {a[0]}")
print(f"Second Index Element: {a[1]}")
print(f"Third Index Element: {a[2]}")
print(f"Fourth Index Element: {a[3]}")
print(f"Firfth Index Element: {a[4]}")


First Index Element: 0
Second Index Element: 1
Third Index Element: 2
Fourth Index Element: 3
Firfth Index Element: 4


In [501]:
arr_index_2d = np.array([
    [11,12,13],
    [14,15,16],
    [31,32,33]
])
print(arr_index_2d[0,0])
print(arr_index_2d[0,1])
print(arr_index_2d[0,2])
print(arr_index_2d[1,0])
print(arr_index_2d[1,1])
print(arr_index_2d[1,2])
print(arr_index_2d[2,0])
print(arr_index_2d[2,1])
print(arr_index_2d[2,2])


11
12
13
14
15
16
31
32
33


In [502]:
# Slicing in array 
cusotm_array = np.array([1,2,3,4,5,6,77,89])
cusotm_array[0::2]


array([ 1,  3,  5, 77])

In [503]:
# Reversing array left to Right
reverse_array = cusotm_array[: : -1]
reverse_array

array([89, 77,  6,  5,  4,  3,  2,  1])

In [504]:
cusotm_array[-3:-1]

array([ 6, 77])

In [505]:
array_2d = np.array([[11,12,13],[21,22,33],[31,32,33]])

In [506]:
array_2d

array([[11, 12, 13],
       [21, 22, 33],
       [31, 32, 33]])

In [507]:
array_2d[1,1:]

array([22, 33])

In [508]:
# Copy and view
new_array = np.array([1,2,3,4,5,6])
copy_array = new_array
print(f"The memory location of new_array is {id(new_array)}")
print(f"The memory location of copy_array is {hex(id(copy_array))}")

The memory location of new_array is 4652312464
The memory location of copy_array is 0x1154ca790


In [509]:
# Copy
new_copy = new_array.copy()
print(f"The memory location of new_copy_array is {(id(new_copy))}")


The memory location of new_copy_array is 4657452624


In [510]:
# View array
view_array = new_array[::2]
test_array = view_array.copy()
print(f"The memory location of new_array is {(id(new_array))}")
print(f"The memory location of view_array is {(id(view_array))}")
print(f"The memory location of test_array is {(id(test_array))}")

print(test_array)
test_array[0] = 12


The memory location of new_array is 4652312464
The memory location of view_array is 4652305840
The memory location of test_array is 4652313520
[1 3 5]


In [511]:
print(new_array)
print(f"The memory location of new_array is {(id(new_array))}")
print(f"The memory location of view_array is {(id(view_array))}")



[1 2 3 4 5 6]
The memory location of new_array is 4652312464
The memory location of view_array is 4652305840


In [512]:
# Memory kati lagiraxa rw Time coplexity kati upto 3D array => Assignment
# Task_2 => User input and create 2D array and print Diagonal elements



In [513]:
dir(new_array)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [514]:

custom_array = np.array([1,2,3,4,5,6,7])
custom_array[-1::-1]


array([7, 6, 5, 4, 3, 2, 1])

In [515]:
pi =3.14
b = np.linspace(0, pi, 3)
print(b)
np.linspace(0,40,12)


[0.   1.57 3.14]


array([ 0.        ,  3.63636364,  7.27272727, 10.90909091, 14.54545455,
       18.18181818, 21.81818182, 25.45454545, 29.09090909, 32.72727273,
       36.36363636, 40.        ])

In [516]:
d = np.exp(b * 1j)
d

array([ 1.00000000e+00+0.j        ,  7.96326711e-04+0.99999968j,
       -9.99998732e-01+0.00159265j])

In [517]:
new_array = np.array([1,2,3,4])
print(new_array.sum())
print(new_array.max())
print(new_array.min())

10
4
1


In [518]:
b = np.arange(16).reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [519]:
# X-axis
print(b.sum(axis=1) )
# Y-axis
print(b.sum(axis=0))

[ 6 22 38 54]
[24 28 32 36]


In [520]:
print(b.min(axis=0))
print(b.min(axis=1))
print(b.max(axis=0))
print(b.max(axis=1))

[0 1 2 3]
[ 0  4  8 12]
[12 13 14 15]
[ 3  7 11 15]


In [521]:
print(b.cumsum(axis=1))
print(b.cumsum(axis=0))


[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]
 [12 25 39 54]]
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]
 [24 28 32 36]]


In [522]:
def f(x,y):
    return 10*x+y

def c(x):
    return 10*x

b = np.fromfunction(f , (4,4) , dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33]])

In [523]:
def c(x):
    return 10 * x

# Create a 1D array using fromfunction
result = np.fromfunction(c, (4,), dtype=int)
result

array([ 0, 10, 20, 30])

In [524]:
class SimpleArray:
    def __init__(self, size):
        self.size = size
        self.data = [None] * size

    def __getitem__(self, index):
        return self.data[index]

    def __setitem__(self, index, value):
        self.data[index] = value

    def insert(self, index, value):
        if isinstance(value, (list, tuple)):  # Check if value is a list or tuple
            if all(isinstance(elem, (list, tuple)) for elem in value):  # Check if all elements are lists or tuples
                # Inserting a multi-dimensional array
                self.data.insert(index, value)
                self.size += 1
            elif all(isinstance(elem, (int, float)) for elem in value):  # Check if all elements are integers or floats
                # Inserting a 1D array
                self.data.insert(index, value)
                self.size += 1
            else:
                print("Error: Insertion of non-array values is not supported")
        else:
            print("Error: Insertion of non-array values is not supported")

    def delete(self, index):
        del self.data[index]
        self.size -= 1

    def update(self, index, value):
        self.data[index] = value

    def traverse(self):
        for i in range(self.size):
            print(self.data[i], end=" ")
        print()

    def sort(self):
        # Move None values to the end
        self.data.sort(key=lambda x: (x is None, x) if isinstance(x, (int, float)) else (False,))

    def search(self, value):
        indices = [i for i, x in enumerate(self.data) if x == value]
        return indices if indices else None


# Test the SimpleArray class with insertion of arrays
arr = SimpleArray(3)
print("Initial array:")
arr.traverse()

# Insertion of 1D array
arr.insert(1, [1, 2, 3])
print("After insertion of 1D array at index 1:")
arr.traverse()

# Insertion of 2D array
arr.insert(2, [[4, 5], [6, 7]])
print("After insertion of 2D array at index 2:")
arr.traverse()

# Insertion of 3D array
arr.insert(3, [[[8, 9], [10, 11]], [[12, 13], [14, 15]]])
print("After insertion of 3D array at index 3:")
arr.traverse()

# Deletion
arr.delete(3)
print("After deletion at index 3:")
arr.traverse()

# Updating
arr.update(1, 20)
print("After updating at index 1:")
arr.traverse()

# Sorting
arr.sort()
print("After sorting:")
arr.traverse()

# Searching
index = arr.search(10)
print("Indices of element 10:", index)


Initial array:
None None None 
After insertion of 1D array at index 1:
None [1, 2, 3] None None 
After insertion of 2D array at index 2:
None [1, 2, 3] [[4, 5], [6, 7]] None None 
After insertion of 3D array at index 3:
None [1, 2, 3] [[4, 5], [6, 7]] [[[8, 9], [10, 11]], [[12, 13], [14, 15]]] None None 
After deletion at index 3:
None [1, 2, 3] [[4, 5], [6, 7]] None None 
After updating at index 1:
None 20 [[4, 5], [6, 7]] None None 
After sorting:
None [[4, 5], [6, 7]] None None 20 
Indices of element 10: None


In [537]:
class SimpleArray:
    def __init__(self, size):
        self.size = size
        self.data = [None] * size

    def __getitem__(self, index):
        return self.data[index]

    def __setitem__(self, index, value):
        self.data[index] = value

    def insert(self, index, value, data_type):
        if isinstance(value, (list, tuple)):  # Check if value is a list or tuple
            if all(isinstance(elem, data_type) for elem in value):  # Check if all elements are of the specified data type
                # Insert the value
                self.data.insert(index, value)
                self.size += 1
            else:
                print("Error: Insertion of non-homogeneous data is not supported")
        else:
            print("Error: Insertion of non-array values is not supported")

    def delete(self, index):
        del self.data[index]
        self.size -= 1

    def update(self, index, value):
        self.data[index] = value

    def traverse(self):
        for i in range(self.size):
            print(self.data[i], end=" ")
        print()

    def sort(self):
        # Move None values to the end
        self.data.sort(key=lambda x: (x is None, x) if isinstance(x, (int, float)) else (False,))

    def search(self, value):
        indices = [i for i, x in enumerate(self.data) if x == value]
        return indices if indices else None


# Test the SimpleArray class with insertion of arrays
arr = SimpleArray(3)
print("Initial array:")
arr.traverse()

# Insertion of 1D array
arr.insert(1, [1, 2, 3], int)
print("After insertion of 1D array at index 1:")
arr.traverse()

# Insertion of 2D array
arr.insert(2, [[4, 5], [6, 7]], int)
print("After insertion of 2D array at index 2:")
arr.traverse()

# Insertion of 3D array
arr.insert(3, [[[8, 9], [10, 11]], [[12, 13], [14, 15]]], int)
print("After insertion of 3D array at index 3:")
arr.traverse()

# Deletion
arr.delete(3)
print("After deletion at index 3:")
arr.traverse()

# Updating
arr.update(1, 20)
print("After updating at index 1:")
arr.traverse()

# Sorting
arr.sort()
print("After sorting:")
arr.traverse()

# Searching
index = arr.search(10)
print("Indices of element 10:", index)


Initial array:
None None None 
After insertion of 1D array at index 1:
None [1, 2, 3] None None 
Error: Insertion of non-homogeneous data is not supported
After insertion of 2D array at index 2:
None [1, 2, 3] None None 
Error: Insertion of non-homogeneous data is not supported
After insertion of 3D array at index 3:
None [1, 2, 3] None None 
After deletion at index 3:
None [1, 2, 3] None 
After updating at index 1:
None 20 None 
After sorting:
None None 20 
Indices of element 10: None
