In [1]:
import numpy as np

In [5]:
array_data = [1,2,3,4,5,6]
array_one = np.array(array_data)
print(array_one)

[1 2 3 4 5 6]


In [6]:
print(type(array_one))

<class 'numpy.ndarray'>


In [8]:
list_two = [
    [1,2,3],
    [4,5,6]
]
array_two = np.array(list_two , dtype='float32')
array_two
# print(type(array_two))

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [9]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.zeros((3,5) , dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [11]:
np.ones((3,5) , dtype='float32')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [12]:
np.full((3,5) , 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [13]:
np.full((3,5) , 4 , dtype='float64')

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [14]:
np.arange(0,20,2)
# 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.random.random((3,3))

array([[0.24403155, 0.96547154, 0.54927547],
       [0.26255639, 0.91027576, 0.97093558],
       [0.32208041, 0.50236516, 0.08208329]])

In [17]:
np.random.normal(0,1,(3,3))

array([[-1.04889554,  2.38184924, -1.51785657],
       [-0.62782595,  0.95783067,  0.46561074],
       [-0.07181709,  0.32838125, -0.55587147]])

In [21]:
np.random.normal(0,1,(3,3))
# Mean 0 and standard deviation in range of one

array([[-0.82219568,  0.22372818, -0.0433363 ],
       [ 1.12469666,  0.35372224, -0.11044871],
       [ 0.02353746,  1.34481251,  1.50165459]])

In [22]:
np.random.randint(1,10,(3,3))

array([[7, 3, 4],
       [9, 7, 8],
       [7, 5, 5]])

In [24]:
array_two.shape


(2, 3)

In [26]:
array_two.size

6

In [27]:
array_two.dtype

dtype('float32')

In [28]:
array_two.itemsize

4

In [29]:
array_two.ndim

2

In [30]:
sample_array = [[1,2,3,4],[5,6,7,8],[9,1,2,3]]
np_array = np.array(sample_array)

In [34]:
print(f"Dimension of the array is : {np_array.ndim}")
print(f"Size of the array is : {np_array.shape}")
print(f"RC of the array is : {np_array.size}")
print(f"Datatype of the array is : {np_array.dtype}")

Dimension of the array is : 2
Size of the array is : (3, 4)
RC of the array is : 12
Datatype of the array is : int64


In [38]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
array_3d
print(f"Dimension of the array is : {array_3d.ndim}")
print(f"Size of the array is : {array_3d.shape}")

Dimension of the array is : 3
Size of the array is : (2, 2, 3)


In [40]:
array_3d = np.array([[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]])
array_3d
print(array_3d.ndim)

4
