In [1]:
import numpy as np

In [3]:
new_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
np.reshape(new_array , (4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
new_array.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [6]:
'''Can we reshape to any shape..?
   => Yes as long as element required for reshaping are equal in both shapes
'''

'Can we reshape to any shape..?\n   => Yes as long as element required for reshaping are equal in both shapes\n'

In [7]:
# Convert 1D array with 8 elements to a 2D array 
array_1D = np.array([1,2,3,4,5,6,7,8])
array_1D.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
array_1D.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
array_1D.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
'''This process raise an exception , since there are 8 elements and (3,3) need 9 elements so raise an exception'''

In [11]:
# Joining array
array_one = np.array([1,2,3,4,5])
array_two = np.array([5,6,7,8,9])


-We pass sequence of arrays that we want to the concatenate() fuunciton.
-After cincat dimension of resulting array will be same as that of the concatenate() function 
-Order of the concat will be based on the order in which array are passed to hte cancat() function
-Synrax
np.concatenate(arr1 ,arr1 , axis=0 oute=none)

In [15]:
array_one = np.array([1,2,3,4,5])
array_two = np.array([5,6,7,8,9])
concat_arr = np.concatenate((array_one , array_two))
concat_arr

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [16]:
# Concat 2D array
array_one_2D = np.array([[1,2,3,4],[5,6,7,8]])
array_two_2D = np.array([[8,0,1,2],[1,2,3,4]])
concat_arr_two = np.concatenate((array_one_2D , array_two_2D))
concat_arr_two

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 0, 1, 2],
       [1, 2, 3, 4]])

In [17]:
np.concatenate((array_one_2D , array_two_2D) , axis=1)

array([[1, 2, 3, 4, 8, 0, 1, 2],
       [5, 6, 7, 8, 1, 2, 3, 4]])

### Splitting array 
- Splitting is reverse operation of joining
- Joining merges multiple arrays into one
- Splitting breaks one array into multiple one
- Can be implemented by using numpy
   - numpy.split()
   - numpy.array_split()
- We pass array we want to split and the number of split
- Sub-array obtained after spliting is only view of the original arrays.
    - Changes made to sub-arrays also reflect hte original array
    -

In [20]:
# Splitting array
array_ = np.array([1,2,3,4,5,6])
np.split(array_ ,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [21]:
np.array_split(array_ , 5)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]

In [28]:
split_array = np.array([[1,2,3],
                        [4,5,6],
                        [7,8,9],
                        [10,11,12],
                        [13,14,15],
                        [16,17,18]])

np.split(split_array ,3)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [26]:
np.split(split_array ,4)

ValueError: array split does not result in an equal division

In [24]:
np.array_split(split_array ,4)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15]]),
 array([[16, 17, 18]])]

In [29]:
np.array_split(split_array ,4 ,axis=1)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]]),
 array([], shape=(6, 0), dtype=int64)]

Numpy  Universal Fujnctions
- Looping over the array performs repeated task like addition , sub , etc on each array element are common 
- Computation time to perform such repeated task increases with relatively larger data.
- Numpy makes this faster by using vectorized operations , implemented through unfuncs
  - Types:
    - Unary Ufuncs
    -Binary Ufincs

Operations : 
np.add() => Element wise addition
np.subtract() => Element Subtraction

In [31]:
# Numpy Universal Function
import time
x1 = np.arange(1 ,1000)
x2 = np.arange(1,1000)

mul = np.zeros(x1.shape)

start_time = time.process_time()

for i in range(len(x1)):
    mul[i] = x1[i] * x2[2]

end_time = time.process_time()

print(end_time - start_time)

0.0005279999999991958


In [ ]:
# Vectorization

In [32]:
a = np.array([1,2,3,4])
b = 2
print(a + b)

[3 4 5 6]


In [33]:
a = np.array([1,2,3])
b = np.array([[10],[20],[30]])

In [34]:
a.shape

(3,)

In [35]:
b.shape

(3, 1)

In [36]:
print(a+b)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [37]:
a = np.array([1,2])
b= np.array([1,2,3])
print(a+b)

ValueError: operands could not be broadcast together with shapes (2,) (3,) 